### ISSUE TITLE
Imagem do mapa com a rota

### ISSUE THREAD

**Issue by rudivels** [Tecnomobele-FGA/SiteSimuladorCarroEletrico#1]
Oi Murilo. Estava vendo a tentativa de colocar um mini mapa no app. Talvez uma estratégia intermediária mais direta é gerar um arquivo JPG ou PNG a partir das rotinas que já funcionam em python e linkar esse mapa no flutter. 
Vou tentar fazer uma rotina simples no python que pega o arquivo GPX e gera uma imagem. 

! pip install geopandas
! pip install folium
! pip install gdal

import geopandas
import folium
import time 
import os
from geopy import distance

nome='Tagua_instei2.gpx'
rota= geopandas.read_file(nome,layer='track_points')
print("Cáluclo de velocidade e tempo")
print("Essa rotina dura alguns minuto !!!")
print(time.ctime())
latlon=[] 
tamanho=len(rota.geometry.x)-1

for i in range(tamanho): 
    latlon.append((rota.geometry.y[i], rota.geometry.x[i]))
    print(".", end='')
print("")
print(time.ctime())   

map = folium.Map(location = [min(rota.bounds.miny) , min(rota.bounds.minx) ], tiles='OpenStreetMap' , zoom_start = 13,width=750, height=500) #, crs='EPSG4326') #, zoom_control=False)
folium.Marker(latlon[0],popup="<i>Mt. Hood Meadows</i>", tooltip="Inicio", icon=folium.Icon(color="green")).add_to(map)
folium.Marker(latlon[len(latlon)-1],popup="<i>Mt. Hood Meadows</i>", tooltip="Fim",icon=folium.Icon(color="red")).add_to(map)
for coord in latlon:
     folium.Circle( location=[ coord[0], coord[1] ], radius=10,  color='brown', fill=True ).add_to( map )
map.fit_bounds([[min(rota.bounds.miny) , min(rota.bounds.minx)], [max(rota.bounds.miny), max(rota.bounds.minx)]])   
map.save('saida.html')

O mapa pode ser interativa mostrando um label com velocidade em cada ponto do mapa, fazendo uma modificação usando "tooltip", 

for coord in latlon:
    folium.Circle( location=[ coord[0], coord[1] ], radius=10,  tooltip= coord[0],
                  color='brown', fill=True ).add_to( map )  

Neste exemplo usei o tooltip = coord[0], mas o correto seria colocar a velocidade...

**Comment by murilopbs** [comment]
Muito bom professor, mas pesquisando acabei achando um pacote do google maps que gera o mapa da trajetória de forma bem simples. Já testei e até agora não apresentou nenhum erro, então fiz um commit atualizando os arquivos do código aqui no github. Também já fiz o upload no site e o mini mapa já está funcionando.

**Comment by rudivels** [comment]
Fechando este issue, pois foi resolvido
